comment: false

coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    patch: off
    project:
      default: off
      one:
        flags: one
      two:
        flags: two

flags:
  one:
    paths:
      - ./index.js
  two:
    paths:
      - ./index2.js